placeholders:
    view_content_data_additional_information:
        items:
            oro_partner_info: ~

items:
    oro_partner_info:
        template: OroPartnerBundle:Partner:infoPlaceholder.html.twig
        attribute_instance_of: [entity, %orocrm_account.account.entity.class%]
